import type { MovementCause, Sale, StockMovementV2, StockOperation } from '@stockflow/contracts';

export interface NamedRecord {
  id?: string;
  productId?: string;
  menuItemId?: string;
  name: string;
}

const UUID = /\b[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}\b/gi;

export function containsUuid(text: string): boolean {
  return new RegExp(UUID).test(text);
}

/** Presentation only: route IDs, command bodies and recorded snapshots stay intact. */
export function readableText(
  text: string | null | undefined,
  ...sources: readonly NamedRecord[][]
): string {
  const names = new Map<string, string>();
  for (const records of sources) {
    for (const record of records) {
      const id = record.id ?? record.productId ?? record.menuItemId;
      if (id && !names.has(id.toLowerCase())) names.set(id.toLowerCase(), record.name);
    }
  }
  return (text ?? '').replace(UUID, (id) => names.get(id.toLowerCase()) ?? '(name unavailable)');
}

export function recordReason(text: string, ...sources: readonly NamedRecord[][]): string {
  // These prefixes are generated by Sales; retain the employee's refund explanation.
  const value = text
    .replace(/^Sale [\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i, 'Sale consumption')
    .replace(/^Refund [\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}:\s*/i, 'Refund: ');
  return readableText(value, ...sources);
}

export function recordTime(createdAt: string): string {
  const date = new Date(createdAt);
  return Number.isNaN(date.getTime())
    ? 'Date unavailable'
    : date.toLocaleString(undefined, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        second: '2-digit',
      });
}

export function saleLabel(sale: Pick<Sale, 'receiptReference' | 'lines' | 'createdAt'>): string {
  if (sale.receiptReference && !containsUuid(sale.receiptReference)) return sale.receiptReference;
  const items = sale.lines
    .map((line) => `${line.quantity} × ${readableText(line.name)}`)
    .join(', ');
  return `${items || 'Sale'} · ${recordTime(sale.createdAt)}`;
}

export function operationKind(kind: MovementCause): string {
  return {
    MANUAL: 'Manual stock adjustment',
    RECEIPT: 'Delivery',
    TRANSFER: 'Stock transfer',
    WASTE: 'Waste',
    COUNT: 'Physical count adjustment',
    SALE: 'Sale consumption',
    SALE_RETURN: 'Sale stock return',
  }[kind];
}

export function operationLabel(
  operation: Pick<StockOperation, 'reference' | 'kind' | 'createdAt'>,
  location: string,
): string {
  if (operation.reference && !containsUuid(operation.reference)) return operation.reference;
  return `${operationKind(operation.kind)} · ${location} · ${recordTime(operation.createdAt)}`;
}

export function movementLabel(movement: StockMovementV2): string {
  if (movement.sourceReference && !containsUuid(movement.sourceReference))
    return movement.sourceReference;
  return `${operationKind(movement.cause)} · ${recordTime(movement.createdAt)}`;
}
